Handle both pet and cattle use cases

diff --git a/ai-bs-vm b/ai-bs-vm
--- a/ai-bs-vm
+++ b/ai-bs-vm
@@ -3,6 +3,9 @@
 # Foreman-enabled Openstack VM
 # Authors:
 #  Nacho Barrientos <nacho.barrientos@cern.ch>
+# Notes:
+#  - This script is meant to be wrapped by ai-bs-pet
+#    and ai-bs-cattle in the near future.
 
 # Exit codes:
 #  0 success
@@ -16,12 +19,18 @@
 
 function dieiffail {
   if [ $1 -ne 0 ]; then
-    if [ ! -z $AIBS_VMUSERDATA_PATH]; then
+    if [ ! -z $AIBS_VMUSERDATA_PATH -a -e $AIBS_VMUSERDATA_PATH ]; then
       rm -f $AIBS_VMUSERDATA_PATH
     fi
     echo "$2";
     exit $3;
   fi
+}
+
+function usage {
+  echo "Usage: $0 <pet|cattle> vmname"
+  echo "Only 'pet' VM type is supported at the moment"
+  exit 1
 }
 
 if [ -z $AIBS_HOSTGROUP_NAME ]; then
@@ -39,26 +48,29 @@ if [ -z $AIBS_SSHKEY_NAME ]; then
   exit 1
 fi
 
-AIBS_HOSTNAME=$1
-
-echo $AIBS_HOSTNAME | egrep -q "\.cern\.ch$"
-if [[ $# -ne 1 || $? -ne 0 ]]; then
-  echo "A CERN-friendly FQDN must be provided as desired hostname"
-  echo "Example: 'higgsbox.cern.ch'. Exiting."
-  exit 1
-fi
-
 if [ -z $OS_USERNAME ]; then
   echo "No OpenStack credentials found. Please source openrc.sh."
   echo "More info: 'man $0'. Exiting..."
   exit 1
 fi
 
-AIBS_VMNAME=$(echo $AIBS_HOSTNAME | sed -e 's/.cern.ch//g')
+# VM name
+# Not a FQDN because it won't match the VM hostname in
+# the cattle usecase
+AIBS_VMNAME=$(echo $2 | sed -e 's/.cern.ch//g')
 
+# VM type
+VMTYPE="vmtype_$1"
+ALLOWED_VMTYPES="vmtype_pet"
+
+echo $ALLOWED_VMTYPES | grep -q $VMTYPE
+[[ $? == 0 ]] || usage
+
+# Cmdline validation
+[[ -z $AIBS_VMNAME ]] && usage
 
 # Foreman Owner
-# (default: "$USER"
+# (default: "$USER")
 AIBS_FOREMAN_OWNER=${AIBS_FOREMAN_OWNER:-"$USER"}
 
 # VM flavor
@@ -72,7 +84,7 @@ AIBS_VMIMAGE_NAME=${AIBS_VMIMAGE_NAME:-"SLC6 Server"}
 # VM base userdata
 AIBS_VMBASEUSERDATA_PATH=${AIBS_VMBASEUSERDATA_PATH:-"/usr/share/ai-tools/userdata/common"}
 
-echo "Trying to bootstrap $AIBS_HOSTNAME..."
+echo "Trying to bootstrap '$AIBS_VMNAME'..."
 
 #
 # User data generation
@@ -83,20 +95,20 @@ echo "Using $AIBS_VMBASEUSERDATA_PATH as template"
 AIBS_VMUSERDATA_PATH=$(mktemp)
 rm $AIBS_VMUSERDATA_PATH
 cp $AIBS_VMBASEUSERDATA_PATH $AIBS_VMUSERDATA_PATH
-sed -i -e "s/%FOREMAN_HOSTGROUP%/$AIBS_HOSTGROUP_NAME/g" $AIBS_VMUSERDATA_PATH
+sed -i -e "s,%FOREMAN_HOSTGROUP%,$AIBS_HOSTGROUP_NAME,g" $AIBS_VMUSERDATA_PATH
 sed -i -e "s/%FOREMAN_ENVIRONMENT%/$AIBS_ENVIRONMENT_NAME/g" $AIBS_VMUSERDATA_PATH
 sed -i -e "s/%FOREMAN_OWNER%/$AIBS_FOREMAN_OWNER/g" $AIBS_VMUSERDATA_PATH
 echo "Done (requested VM owner is '$AIBS_FOREMAN_OWNER')"
 
 #
-# Host staging
+# Host staging if pet VM
 #
 
-echo "Staging host on certmgr..."
-certmgr-stage --host $AIBS_HOSTNAME
-
-dieiffail $? "Failed to stage host. Exiting" 20;
-
+if [ $VMTYPE == "vmtype_pet" ]; then
+  echo "Staging host on certmgr..."
+  certmgr-stage --host $AIBS_VMNAME.cern.ch
+  dieiffail $? "Failed to stage host. Exiting" 20;
+fi
 
 #
 # VM spawning
@@ -113,10 +125,12 @@ nova boot --flavor $AIBS_VMFLAVOR_NAME --image "$AIBS_VMIMAGE_NAME" \
 rm -f $AIBS_VMUSERDATA_PATH
 
 if [ $? -ne 0 ]; then
-  echo "Failed to create VM. Unstaging host...";
-  certmgr-stage --unstage --host $AIBS_HOSTNAME
-  dieiffail $? "Unstage process failed." 50
-  exit 30
+  if [ $VMTYPE == "vmtype_pet" ]; then
+    echo "Failed to create VM. Unstaging host...";
+    certmgr-stage --unstage --host $AIBS_VMNAME
+    dieiffail $? "Unstage process failed." 50
+    exit 30
+  fi
 fi
 
 echo "VM booting. Nothing else to do."
