Stop the script if cern-get-sso-cookie fails

diff --git a/ai-bs-pet b/ai-bs-pet
--- a/ai-bs-pet
+++ b/ai-bs-pet
@@ -10,6 +10,7 @@
 #  10 Foreman registration failed
 #  20 Host staging failed
 #  30 VM creation failed 
+#  40 Cookie generation failed
 #  50 Other errors
 
 # Notes:
@@ -81,6 +82,7 @@ echo "Will feed userdata located in $AIBS_VMUSERDATA_PATH"
 if [ ! -r $AIBS_COOKIEJAR_PATH ]; then
   echo "Cookiejar not found or not readable. Getting it..."
   cern-get-sso-cookie --krb -u https://judy.cern.ch -o $AIBS_COOKIEJAR_PATH -r
+  dieiffail $? "Failed to get SSO cookie. Exiting" 40;
 fi
 
 #
diff --git a/ai-kill-pet b/ai-kill-pet
--- a/ai-kill-pet
+++ b/ai-kill-pet
@@ -9,6 +9,7 @@
 #  1 user input failed
 #  10 VM deletion failed
 #  20 Foreman deregistration failed
+#  30 Cookie generation failed
 #  50 Other errors
 
 # Known bugs:
@@ -60,6 +61,7 @@ dieiffail $? "Failed to terminate VM. Exiting..." 10;
 if [ ! -r $AIBS_COOKIEJAR_PATH ]; then
   echo "Cookiejar not found or not readable. Getting it..."
   cern-get-sso-cookie --krb -u https://judy.cern.ch -o $AIBS_COOKIEJAR_PATH -r
+  dieiffail $? "Failed to get SSO cookie. Exiting" 30;
 fi
 
 
