Remove bits related to pet VMs

diff --git a/ai-bs-vm b/ai-bs-vm
--- a/ai-bs-vm
+++ b/ai-bs-vm
@@ -24,13 +24,6 @@ function dieiffail {
   fi
 }
 
-function usage {
-  echo "Usage: $0 <pet|cattle> vmname"
-  echo "Note: Only 'pet' VM type is supported at the moment"
-  exit 1
-}
-
-
 if [ -z $AIBS_HOSTGROUP_NAME ]; then
   echo "Hostgroup name must be specified via AIBS_HOSTGROUP_NAME environment variable."
   echo "Examples: 'spare', 'myhostgroup/spare', 'lxbatch/workers/spare'"
@@ -142,11 +135,9 @@ echo "Done"
 # Host staging if pet VM
 #
 
-if [ $VMTYPE == "vmtype_pet" ]; then
-  echo "Staging host on certmgr..."
-  certmgr-stage --host $AIBS_VMNAME.cern.ch
-  dieiffail $? "Failed to stage host. Exiting" 20;
-fi
+echo "Staging host on certmgr..."
+certmgr-stage --host $AIBS_VMNAME.cern.ch
+dieiffail $? "Failed to stage host. Exiting" 20;
 
 #
 # VM spawning
@@ -163,12 +154,10 @@ nova boot --flavor $AIBS_VMFLAVOR_NAME --image "$AIBS_VMIMAGE_NAME" \
   $METAPARAMS $AIBS_VMNAME
 
 if [ $? -ne 0 ]; then
-  if [ $VMTYPE == "vmtype_pet" ]; then
-    echo "Failed to create VM. Unstaging host...";
-    certmgr-stage --unstage --host $AIBS_VMNAME.cern.ch
-    dieiffail $? "Unstage process failed." 50
-    exit 30
-  fi
+  echo "Failed to create VM. Unstaging host...";
+  certmgr-stage --unstage --host $AIBS_VMNAME.cern.ch
+  dieiffail $? "Unstage process failed." 50
+  exit 30
 fi
 
 rm -f $AIBS_VMUSERDATA_PATH
